#!/bin/bash
# Build CSV/_index.js — embeds the first .csv file from each subfolder of CSV/
# into a single JS file, so dashboards can load default data when opened via file://
# (where fetch() is blocked by Chrome).
#
# Usage: ./build-csv-index.sh
# Rerun this script whenever you add/replace CSV files.

set -e
cd "$(dirname "$0")"

OUT="CSV/_index.js"
TMP="$(mktemp)"

echo "// Auto-generated by build-csv-index.sh — do not edit by hand." > "$TMP"
echo "// Each entry: { name: <filename>, content: <base64-encoded CSV bytes> }" >> "$TMP"
echo "window.__ARROWPUZZLE_CSV__ = {" >> "$TMP"

found_any=0
for dir in CSV/*/; do
  [ -d "$dir" ] || continue
  folder=$(basename "$dir")
  # Newest .csv (by mtime) inside this folder, non-recursive
  first_csv=$(ls -t "$dir"*.csv 2>/dev/null | head -n 1)
  if [ -z "$first_csv" ]; then
    echo "  [skip] $folder/ — không có file CSV"
    continue
  fi
  fname=$(basename "$first_csv")
  b64=$(base64 < "$first_csv" | tr -d '\n')
  size=$(wc -c < "$first_csv" | tr -d ' ')
  # Escape double-quotes and backslashes inside folder/fname for JS string
  esc_folder=$(printf '%s' "$folder" | sed 's/\\/\\\\/g; s/"/\\"/g')
  esc_fname=$(printf '%s' "$fname" | sed 's/\\/\\\\/g; s/"/\\"/g')
  printf '  "%s": { name: "%s", content: "%s" },\n' \
    "$esc_folder" "$esc_fname" "$b64" >> "$TMP"
  echo "  [ok]   $folder/$fname (${size} bytes)"
  found_any=1
done

echo "};" >> "$TMP"
mv "$TMP" "$OUT"

if [ "$found_any" -eq 1 ]; then
  echo ""
  echo "Generated $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)"
  echo "Mở dashboard qua file:// → sẽ tự load data từ index này."
else
  echo ""
  echo "Không tìm thấy CSV nào — $OUT vẫn được tạo nhưng rỗng."
fi
